package nextbus.predictiondist.tasks;

public enum IdeaType {
	NORMAL_LOOPING, 
	TEMP_MAP,
	LOCAL_KEY_PREDICATE,
	DIST_QUERY_STOP_KEY,
	DIST_QUERY_STOP_PRED,
	MULTI_MAP,
	LOOKUP_MULTI_MAPS,
	LOCAL_MULTI_MAPS_USING_LISTENRS,
	LOCAL_MULTI_MAPS,
	LOCAL_SINGLE_MULTI_MAPS,
	LOCAL_SINGLE_MULTI_MAPS__LISTENRS,
	POPULATE_MULTI_MAPS,
	USE_ACTUAL_STOP_KEYS,
	;
}
